@echo off
echo Fetching latest dev branch...
git checkout develop
git pull origin develop
echo Done!...
echo Starting InSys!...
start cmd /k "echo Starting Front-End Application... && npm i && npm run dev"
start cmd /k "echo Starting Back-End Application... && cd server && npm i && npm run dev"
echo running...
pause